masterCollection/urls.py
from django.conf.urls import patterns, url

from masterCollection import views

urlpatterns = patterns('',
    url(r'^$',                           views.IndexView.as_view(),  name='index'),
    url(r'^master/(?P<pk>\d+)/$',        views.MasterView.as_view(), name='master'),
)

moscowMasters/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'moscowMasters.views.home', name='home'),
    # url(r'^moscowMasters/', include('moscowMasters.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('masterCollection.urls', namespace="masterCollection")),
)

masterCollection/models.py
from django.db import models
from django.contrib.auth.models import User

# Edited only by admins
class Service(models.Model):
    url_name = models.SlugField(max_length=50, primary_key=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

class Master(models.Model):
    name        = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    email       = models.EmailField(max_length=254, unique=True)
    services    = models.ManyToManyField(Service, through='MasterService')
    user        = models.OneToOneField(User, null=True)
    published   = models.BooleanField(default=False)
    address     = models.CharField(max_length=1000, blank=True)

    def __unicode__(self):
        return self.name

class MasterService(models.Model):
    master = models.ForeignKey(Master)
    service = models.ForeignKey(Service)

    price = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        unique_together=("master", "service")

masterCollection/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from masterCollection.models import Master, Service, MasterService

class IndexView(generic.ListView):
    template_name = 'masterCollection/index.html'
    context_object_name = 'master_list'

    def search_string(self):
        return self.request.GET.get('search_string')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['search_string'] = self.search_string()
        return context

    def get_queryset(self):

        lookups = { 'published' : 'True' }
        search_string = self.search_string()
        if not search_string == None:
            lookups['name__icontains'] = search_string

        print lookups

        return Master.objects.filter(**lookups)

class MasterView(generic.DetailView):
    model = Master
    template_name = 'masterCollection/master.html'

masterCollection/templates/masterCollection/base.html
{% extends "base.html" %}

{% block navigation %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'masterCollection:index' %}">Мастера Москвы</a>
        </div>

        <div class="collapse navbar-collapse navbar-ex1-collapse">

        <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'masterCollection:index' %}">
            <div class="form-group">
                {% if search_string %}
                    <input type="text" class="form-control" name="search_string" value="{{ search_string }}">
                {% else %}
                    <input type="text" class="form-control" placeholder="Search" name="search_string">
                {% endif %}
            </div>
        <button type="submit" class="btn btn-default">Submit</button>
</form>

        </div>

    </nav>
{% endblock %}

masterCollection/templates/masterCollection/index.html
{% extends "masterCollection/base.html" %}

{% block title %}Список мастеров{% endblock %}

{% block content %}
    {% if master_list %}
        <ul class="list-group">
        {% for master in master_list %}
            <li class="list-group-item"><a href= "{% url 'masterCollection:master' master.id %}">{{ master.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No masters in database.</p>
    {% endif %}
{% endblock %}

masterCollection/templates/masterCollection/master.html
{% extends "masterCollection/base.html" %}

{% block title %}Мастера Москвы: {{ master.name }}{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>{{ master.name }}</h1>
        </div>
        <div class="panel-body">
            <div class="row"></div>
                <div class="col-sm-7"><p>{{ master.description }}</p></div>

                {% if master.address and master.address.strip %}
                    <div class="col-sm-5">

                        <script src=http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU type="text/javascript"></script>
                        <div id="map" style="width: 100%; height: 300px"></div>

                        <script type="text/javascript">
                            ymaps.ready(init);
                            var myMap, myPlacemark;

                            function init() {
                                myMap = new ymaps.Map ("map", {
                                        center: [55.76, 37.64], // Центр Москвы по умолчанию, пока мы не загрузили точку
                                        zoom: 7
                                    });

                                myGeocoder = ymaps.geocode("{{ master.address }}");

                                myGeocoder.then(
                                    function(res) {
                                        var nearest = res.geoObjects.get(0);

                                        nearest.properties.set('iconContent', "{{ master.name }}");
                                        nearest.options.set('preset', 'twirl#redStretchyIcon');

                                        myMap.geoObjects.add(nearest);
                                        myMap.setCenter(nearest.geometry.getCoordinates());
                                        myMap.setZoom(15);
                                    }
                                    // TODO: Сделать нормальную обработку ошибок
                                );

                                myMap.geoObjects.add(myPlacemark);
                            }
                        </script>
                    </div>
                {% endif %}

            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Услуга
                    </th>
                    <th>
                        Цена
                    </th>
                </tr>
            </thead>
            {% for master_service in master.masterservice_set.iterator %}
                <tr>
                    <td>
                        {{ master_service.service.name }}
                    </td>
                    <td>
                        {{ master_service.price }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang='ru'>
<head>
    <title>{% block title %}Мастера Москвы{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">

</head>

<body>
    <!-- jQuery -->
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <div class="container">
        <div id="navigation">{% block navigation %}{% endblock %}</div>
        <div id="content">{% block content %}{% endblock %}</div>
    </div>
</body>

</html>